# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clearTx = QtWidgets.QPushButton(self.centralwidget)
        self.clearTx.setGeometry(QtCore.QRect(10, 240, 75, 23))
        self.clearTx.setObjectName("clearTx")
        self.conN = QtWidgets.QComboBox(self.centralwidget)
        self.conN.setGeometry(QtCore.QRect(50, 280, 69, 22))
        self.conN.setObjectName("conN")
        self.clearRx = QtWidgets.QPushButton(self.centralwidget)
        self.clearRx.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.clearRx.setObjectName("clearRx")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 120, 36, 16))
        self.label.setObjectName("label")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 70, 89, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 90, 89, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 54, 12))
        self.label_2.setObjectName("label_2")
        self.conB = QtWidgets.QComboBox(self.centralwidget)
        self.conB.setGeometry(QtCore.QRect(50, 310, 69, 22))
        self.conB.setObjectName("conB")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 290, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 320, 54, 12))
        self.label_4.setObjectName("label_4")
        self.Openserialbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Openserialbtn.setGeometry(QtCore.QRect(10, 340, 111, 31))
        self.Openserialbtn.setObjectName("Openserialbtn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 420, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 440, 54, 12))
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(140, 20, 521, 151))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 220, 521, 111))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 340, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 460, 621, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.RxCount = QtWidgets.QLineEdit(self.centralwidget)
        self.RxCount.setGeometry(QtCore.QRect(30, 440, 81, 21))
        self.RxCount.setObjectName("RxCount")
        self.TxCount = QtWidgets.QLineEdit(self.centralwidget)
        self.TxCount.setGeometry(QtCore.QRect(30, 410, 81, 21))
        self.TxCount.setObjectName("TxCount")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 380, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.conN.raise_()
        self.clearRx.raise_()
        self.label.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.label_2.raise_()
        self.conB.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.Openserialbtn.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.pushButton.raise_()
        self.TxCount.raise_()
        self.RxCount.raise_()
        self.lineEdit.raise_()
        self.clearTx.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menu.addAction(self.actionHelp)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clearTx.setText(_translate("MainWindow", "清空发送"))
        self.clearRx.setText(_translate("MainWindow", "清空接收"))
        self.label.setText(_translate("MainWindow", "接收区"))
        self.radioButton_3.setText(_translate("MainWindow", "文本"))
        self.radioButton_4.setText(_translate("MainWindow", "HEX"))
        self.label_2.setText(_translate("MainWindow", "发送"))
        self.label_3.setText(_translate("MainWindow", "串口"))
        self.label_4.setText(_translate("MainWindow", "波特率"))
        self.Openserialbtn.setText(_translate("MainWindow", "打开串口"))
        self.label_5.setText(_translate("MainWindow", "Tx："))
        self.label_6.setText(_translate("MainWindow", "Rx："))
        self.pushButton.setText(_translate("MainWindow", "发送数据"))
        self.pushButton_2.setText(_translate("MainWindow", "关闭串口"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionHelp.setText(_translate("MainWindow", "help"))

